### ISSUE TITLE
How to enable the cv fit on one page?

### ISSUE THREAD

**Issue by fuhailin** [themagicalmammal/Resume#4]
Thanks, Nanda! I'm trying to use your CV template, when I modified some contents, the output separate two pages automatically, how could I force the output to fit on one page?

**Comment by themagicalmammal** [comment]
Is the other page a empty page?

**Comment by fuhailin** [comment]
No, the name and contracts info on first page, others on second page

**Comment by themagicalmammal** [comment]
You have to fix my removing somethings or send me a link here I will have a look into it.

**Comment by themagicalmammal** [comment]
You have to fix header size.

**Comment by xiazeyu** [comment]
When set the first educaton to:

```
% Education
\cvsection{Education} 

\subsection{Massachusetts Institute of Technology}
```

This issue can then be reproduced.

**Comment by xiazeyu** [comment]
Ohh, I found that is because the page is too full, making the content and header in seperate pages.
